build-and-deploy:
  runs-on: ubuntu-latest
  needs: test
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} .

    - name: Copy Docker image to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        docker save ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} | gzip | ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST "gunzip | docker load"

    - name: Deploy on server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST '
        docker-compose down &&
        docker-compose up -d
        '
